stock CreateTaiXiuTD(playerid) {
    // Form nen chung
    TxMain[playerid] = CreatePlayerTextDraw(playerid, 320.0, 114.0, "_");
    PlayerTextDrawFont(playerid, TxMain[playerid], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, TxMain[playerid], 0.6, 23.8);
    PlayerTextDrawTextSize(playerid, TxMain[playerid], 272.5, 415.0);
    PlayerTextDrawSetOutline(playerid, TxMain[playerid], 1);
    PlayerTextDrawSetShadow(playerid, TxMain[playerid], 0);
    PlayerTextDrawAlignment(playerid, TxMain[playerid], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, TxMain[playerid], -1);
    PlayerTextDrawBackgroundColour(playerid, TxMain[playerid], 255);
    PlayerTextDrawBoxColour(playerid, TxMain[playerid], 135);
    PlayerTextDrawUseBox(playerid, TxMain[playerid], bool:1);
    PlayerTextDrawSetProportional(playerid, TxMain[playerid], bool:1);
    PlayerTextDrawSetSelectable(playerid, TxMain[playerid], bool:0);

    TaiXiuTD[playerid][0] = CreatePlayerTextDraw(playerid, 154.0, 117.0, "_");
    PlayerTextDrawFont(playerid, TaiXiuTD[playerid][0], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, TaiXiuTD[playerid][0], 0.6, 15.6);
    PlayerTextDrawTextSize(playerid, TaiXiuTD[playerid][0], 309.0, 77.5);
    PlayerTextDrawSetOutline(playerid, TaiXiuTD[playerid][0], 1);
    PlayerTextDrawSetShadow(playerid, TaiXiuTD[playerid][0], 0);
    PlayerTextDrawAlignment(playerid, TaiXiuTD[playerid][0], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, TaiXiuTD[playerid][0], -1);
    PlayerTextDrawBackgroundColour(playerid, TaiXiuTD[playerid][0], 255);
    PlayerTextDrawBoxColour(playerid, TaiXiuTD[playerid][0], 65290);
    PlayerTextDrawUseBox(playerid, TaiXiuTD[playerid][0], bool:1);
    PlayerTextDrawSetProportional(playerid, TaiXiuTD[playerid][0], bool:1);
    PlayerTextDrawSetSelectable(playerid, TaiXiuTD[playerid][0], bool:0);

    TaiXiuTD[playerid][1] = CreatePlayerTextDraw(playerid, 472.0, 117.0, "TOP WIN");
    PlayerTextDrawFont(playerid, TaiXiuTD[playerid][1], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, TaiXiuTD[playerid][1], 0.3, 1.5);
    PlayerTextDrawTextSize(playerid, TaiXiuTD[playerid][1], 400.0, 100.0);
    PlayerTextDrawSetOutline(playerid, TaiXiuTD[playerid][1], 1);
    PlayerTextDrawSetShadow(playerid, TaiXiuTD[playerid][1], 0);
    PlayerTextDrawAlignment(playerid, TaiXiuTD[playerid][1], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, TaiXiuTD[playerid][1], TX_COLOR_PINK);
    PlayerTextDrawBackgroundColour(playerid, TaiXiuTD[playerid][1], 255);
    PlayerTextDrawBoxColour(playerid, TaiXiuTD[playerid][1], -1378294222);
    PlayerTextDrawUseBox(playerid, TaiXiuTD[playerid][1], bool:1);
    PlayerTextDrawSetProportional(playerid, TaiXiuTD[playerid][1], bool:1);
    PlayerTextDrawSetSelectable(playerid, TaiXiuTD[playerid][1], bool:0);

    TaiXiuTD[playerid][2] = CreatePlayerTextDraw(playerid, 472.0, 144.0, "_");
    PlayerTextDrawFont(playerid, TaiXiuTD[playerid][2], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, TaiXiuTD[playerid][2], 0.6, 20.2);
    PlayerTextDrawTextSize(playerid, TaiXiuTD[playerid][2], 298.5, 106.5);
    PlayerTextDrawSetOutline(playerid, TaiXiuTD[playerid][2], 1);
    PlayerTextDrawSetShadow(playerid, TaiXiuTD[playerid][2], 0);
    PlayerTextDrawAlignment(playerid, TaiXiuTD[playerid][2], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, TaiXiuTD[playerid][2], -1);
    PlayerTextDrawBackgroundColour(playerid, TaiXiuTD[playerid][2], 255);
    PlayerTextDrawBoxColour(playerid, TaiXiuTD[playerid][2], -1378294232);
    PlayerTextDrawUseBox(playerid, TaiXiuTD[playerid][2], bool:1);
    PlayerTextDrawSetProportional(playerid, TaiXiuTD[playerid][2], bool:1);
    PlayerTextDrawSetSelectable(playerid, TaiXiuTD[playerid][2], bool:0);

    TaiXiuTD[playerid][3] = CreatePlayerTextDraw(playerid, 423.0, 151.0, "1");
    PlayerTextDrawFont(playerid, TaiXiuTD[playerid][3], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, TaiXiuTD[playerid][3], 0.4, 1.2);
    PlayerTextDrawTextSize(playerid, TaiXiuTD[playerid][3], 400.0, 12.0);
    PlayerTextDrawSetOutline(playerid, TaiXiuTD[playerid][3], 1);
    PlayerTextDrawSetShadow(playerid, TaiXiuTD[playerid][3], 0);
    PlayerTextDrawAlignment(playerid, TaiXiuTD[playerid][3], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, TaiXiuTD[playerid][3], -1);
    PlayerTextDrawBackgroundColour(playerid, TaiXiuTD[playerid][3], 255);
    PlayerTextDrawBoxColour(playerid, TaiXiuTD[playerid][3], 50);
    PlayerTextDrawUseBox(playerid, TaiXiuTD[playerid][3], bool:0);
    PlayerTextDrawSetProportional(playerid, TaiXiuTD[playerid][3], bool:1);
    PlayerTextDrawSetSelectable(playerid, TaiXiuTD[playerid][3], bool:0);

    TaiXiuTD[playerid][4] = CreatePlayerTextDraw(playerid, 424.0, 177.0, "2");
    PlayerTextDrawFont(playerid, TaiXiuTD[playerid][4], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, TaiXiuTD[playerid][4], 0.4, 1.2);
    PlayerTextDrawTextSize(playerid, TaiXiuTD[playerid][4], 400.0, 12.0);
    PlayerTextDrawSetOutline(playerid, TaiXiuTD[playerid][4], 1);
    PlayerTextDrawSetShadow(playerid, TaiXiuTD[playerid][4], 0);
    PlayerTextDrawAlignment(playerid, TaiXiuTD[playerid][4], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, TaiXiuTD[playerid][4], -1);
    PlayerTextDrawBackgroundColour(playerid, TaiXiuTD[playerid][4], 255);
    PlayerTextDrawBoxColour(playerid, TaiXiuTD[playerid][4], 50);
    PlayerTextDrawUseBox(playerid, TaiXiuTD[playerid][4], bool:0);
    PlayerTextDrawSetProportional(playerid, TaiXiuTD[playerid][4], bool:1);
    PlayerTextDrawSetSelectable(playerid, TaiXiuTD[playerid][4], bool:0);

    TaiXiuTD[playerid][5] = CreatePlayerTextDraw(playerid, 424.0, 203.0, "3");
    PlayerTextDrawFont(playerid, TaiXiuTD[playerid][5], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, TaiXiuTD[playerid][5], 0.4, 1.2);
    PlayerTextDrawTextSize(playerid, TaiXiuTD[playerid][5], 400.0, 12.0);
    PlayerTextDrawSetOutline(playerid, TaiXiuTD[playerid][5], 1);
    PlayerTextDrawSetShadow(playerid, TaiXiuTD[playerid][5], 0);
    PlayerTextDrawAlignment(playerid, TaiXiuTD[playerid][5], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, TaiXiuTD[playerid][5], -1);
    PlayerTextDrawBackgroundColour(playerid, TaiXiuTD[playerid][5], 255);
    PlayerTextDrawBoxColour(playerid, TaiXiuTD[playerid][5], 50);
    PlayerTextDrawUseBox(playerid, TaiXiuTD[playerid][5], bool:0);
    PlayerTextDrawSetProportional(playerid, TaiXiuTD[playerid][5], bool:1);
    PlayerTextDrawSetSelectable(playerid, TaiXiuTD[playerid][5], bool:0);

    TaiXiuTD[playerid][6] = CreatePlayerTextDraw(playerid, 424.0, 229.0, "4");
    PlayerTextDrawFont(playerid, TaiXiuTD[playerid][6], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, TaiXiuTD[playerid][6], 0.4, 1.2);
    PlayerTextDrawTextSize(playerid, TaiXiuTD[playerid][6], 400.0, 12.0);
    PlayerTextDrawSetOutline(playerid, TaiXiuTD[playerid][6], 1);
    PlayerTextDrawSetShadow(playerid, TaiXiuTD[playerid][6], 0);
    PlayerTextDrawAlignment(playerid, TaiXiuTD[playerid][6], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, TaiXiuTD[playerid][6], -1);
    PlayerTextDrawBackgroundColour(playerid, TaiXiuTD[playerid][6], 255);
    PlayerTextDrawBoxColour(playerid, TaiXiuTD[playerid][6], 50);
    PlayerTextDrawUseBox(playerid, TaiXiuTD[playerid][6], bool:0);
    PlayerTextDrawSetProportional(playerid, TaiXiuTD[playerid][6], bool:1);
    PlayerTextDrawSetSelectable(playerid, TaiXiuTD[playerid][6], bool:0);

    TaiXiuTD[playerid][7] = CreatePlayerTextDraw(playerid, 424.0, 256.0, "5");
    PlayerTextDrawFont(playerid, TaiXiuTD[playerid][7], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, TaiXiuTD[playerid][7], 0.4, 1.2);
    PlayerTextDrawTextSize(playerid, TaiXiuTD[playerid][7], 400.0, 12.0);
    PlayerTextDrawSetOutline(playerid, TaiXiuTD[playerid][7], 1);
    PlayerTextDrawSetShadow(playerid, TaiXiuTD[playerid][7], 0);
    PlayerTextDrawAlignment(playerid, TaiXiuTD[playerid][7], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, TaiXiuTD[playerid][7], -1);
    PlayerTextDrawBackgroundColour(playerid, TaiXiuTD[playerid][7], 255);
    PlayerTextDrawBoxColour(playerid, TaiXiuTD[playerid][7], 50);
    PlayerTextDrawUseBox(playerid, TaiXiuTD[playerid][7], bool:0);
    PlayerTextDrawSetProportional(playerid, TaiXiuTD[playerid][7], bool:1);
    PlayerTextDrawSetSelectable(playerid, TaiXiuTD[playerid][7], bool:0);

    TaiXiuTD[playerid][8] = CreatePlayerTextDraw(playerid, 424.0, 283.0, "6");
    PlayerTextDrawFont(playerid, TaiXiuTD[playerid][8], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, TaiXiuTD[playerid][8], 0.4, 1.2);
    PlayerTextDrawTextSize(playerid, TaiXiuTD[playerid][8], 400.0, 12.0);
    PlayerTextDrawSetOutline(playerid, TaiXiuTD[playerid][8], 1);
    PlayerTextDrawSetShadow(playerid, TaiXiuTD[playerid][8], 0);
    PlayerTextDrawAlignment(playerid, TaiXiuTD[playerid][8], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, TaiXiuTD[playerid][8], -1);
    PlayerTextDrawBackgroundColour(playerid, TaiXiuTD[playerid][8], 255);
    PlayerTextDrawBoxColour(playerid, TaiXiuTD[playerid][8], 50);
    PlayerTextDrawUseBox(playerid, TaiXiuTD[playerid][8], bool:0);
    PlayerTextDrawSetProportional(playerid, TaiXiuTD[playerid][8], bool:1);
    PlayerTextDrawSetSelectable(playerid, TaiXiuTD[playerid][8], bool:0);

    TaiXiuTD[playerid][9] = CreatePlayerTextDraw(playerid, 424.0, 310.0, "7");
    PlayerTextDrawFont(playerid, TaiXiuTD[playerid][9], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, TaiXiuTD[playerid][9], 0.4, 1.2);
    PlayerTextDrawTextSize(playerid, TaiXiuTD[playerid][9], 400.0, 12.0);
    PlayerTextDrawSetOutline(playerid, TaiXiuTD[playerid][9], 1);
    PlayerTextDrawSetShadow(playerid, TaiXiuTD[playerid][9], 0);
    PlayerTextDrawAlignment(playerid, TaiXiuTD[playerid][9], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, TaiXiuTD[playerid][9], -1);
    PlayerTextDrawBackgroundColour(playerid, TaiXiuTD[playerid][9], 255);
    PlayerTextDrawBoxColour(playerid, TaiXiuTD[playerid][9], 50);
    PlayerTextDrawUseBox(playerid, TaiXiuTD[playerid][9], bool:0);
    PlayerTextDrawSetProportional(playerid, TaiXiuTD[playerid][9], bool:1);
    PlayerTextDrawSetSelectable(playerid, TaiXiuTD[playerid][9], bool:0);

    TaiXiuTD[playerid][10] = CreatePlayerTextDraw(playerid, 263.0, 132.0, "_");
    PlayerTextDrawFont(playerid, TaiXiuTD[playerid][10], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, TaiXiuTD[playerid][10], 0.6, 14.0);
    PlayerTextDrawTextSize(playerid, TaiXiuTD[playerid][10], 310.0, 129.0);
    PlayerTextDrawSetOutline(playerid, TaiXiuTD[playerid][10], 1);
    PlayerTextDrawSetShadow(playerid, TaiXiuTD[playerid][10], 0);
    PlayerTextDrawAlignment(playerid, TaiXiuTD[playerid][10], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, TaiXiuTD[playerid][10], -1);
    PlayerTextDrawBackgroundColour(playerid, TaiXiuTD[playerid][10], 255);
    PlayerTextDrawBoxColour(playerid, TaiXiuTD[playerid][10], 1296911716);
    PlayerTextDrawUseBox(playerid, TaiXiuTD[playerid][10], bool:1);
    PlayerTextDrawSetProportional(playerid, TaiXiuTD[playerid][10], bool:1);
    PlayerTextDrawSetSelectable(playerid, TaiXiuTD[playerid][10], bool:0);

    TaiXiuTD[playerid][11] = CreatePlayerTextDraw(playerid, 372.0, 117.0, "_");
    PlayerTextDrawFont(playerid, TaiXiuTD[playerid][11], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, TaiXiuTD[playerid][11], 0.6, 15.7);
    PlayerTextDrawTextSize(playerid, TaiXiuTD[playerid][11], 309.0, 77.5);
    PlayerTextDrawSetOutline(playerid, TaiXiuTD[playerid][11], 1);
    PlayerTextDrawSetShadow(playerid, TaiXiuTD[playerid][11], 0);
    PlayerTextDrawAlignment(playerid, TaiXiuTD[playerid][11], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, TaiXiuTD[playerid][11], -1);
    PlayerTextDrawBackgroundColour(playerid, TaiXiuTD[playerid][11], 255);
    PlayerTextDrawBoxColour(playerid, TaiXiuTD[playerid][11], -16777206);
    PlayerTextDrawUseBox(playerid, TaiXiuTD[playerid][11], bool:1);
    PlayerTextDrawSetProportional(playerid, TaiXiuTD[playerid][11], bool:1);
    PlayerTextDrawSetSelectable(playerid, TaiXiuTD[playerid][11], bool:0);

    TaiXiuTD[playerid][12] = CreatePlayerTextDraw(playerid, 152.0, 116.0, "TAI");
    PlayerTextDrawFont(playerid, TaiXiuTD[playerid][12], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, TaiXiuTD[playerid][12], 0.6, 2.3);
    PlayerTextDrawTextSize(playerid, TaiXiuTD[playerid][12], 400.0, 73.0);
    PlayerTextDrawSetOutline(playerid, TaiXiuTD[playerid][12], 1);
    PlayerTextDrawSetShadow(playerid, TaiXiuTD[playerid][12], 0);
    PlayerTextDrawAlignment(playerid, TaiXiuTD[playerid][12], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, TaiXiuTD[playerid][12], 65535);
    PlayerTextDrawBackgroundColour(playerid, TaiXiuTD[playerid][12], -1);
    PlayerTextDrawBoxColour(playerid, TaiXiuTD[playerid][12], 50);
    PlayerTextDrawUseBox(playerid, TaiXiuTD[playerid][12], bool:0);
    PlayerTextDrawSetProportional(playerid, TaiXiuTD[playerid][12], bool:1);
    PlayerTextDrawSetSelectable(playerid, TaiXiuTD[playerid][12], bool:0);

    TaiXiuTD[playerid][13] = CreatePlayerTextDraw(playerid, 372.0, 116.0, "XIU");
    PlayerTextDrawFont(playerid, TaiXiuTD[playerid][13], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, TaiXiuTD[playerid][13], 0.6, 2.3);
    PlayerTextDrawTextSize(playerid, TaiXiuTD[playerid][13], 400.0, 73.0);
    PlayerTextDrawSetOutline(playerid, TaiXiuTD[playerid][13], 1);
    PlayerTextDrawSetShadow(playerid, TaiXiuTD[playerid][13], 0);
    PlayerTextDrawAlignment(playerid, TaiXiuTD[playerid][13], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, TaiXiuTD[playerid][13], -16776961);
    PlayerTextDrawBackgroundColour(playerid, TaiXiuTD[playerid][13], -1);
    PlayerTextDrawBoxColour(playerid, TaiXiuTD[playerid][13], 50);
    PlayerTextDrawUseBox(playerid, TaiXiuTD[playerid][13], bool:0);
    PlayerTextDrawSetProportional(playerid, TaiXiuTD[playerid][13], bool:1);
    PlayerTextDrawSetSelectable(playerid, TaiXiuTD[playerid][13], bool:0);

    TaiXiuTD[playerid][14] = CreatePlayerTextDraw(playerid, 263.0, 114.0, "Ket Qua Moi Nhat");
    PlayerTextDrawFont(playerid, TaiXiuTD[playerid][14], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, TaiXiuTD[playerid][14], 0.2, 1.1);
    PlayerTextDrawTextSize(playerid, TaiXiuTD[playerid][14], 320.0, 97.0);
    PlayerTextDrawSetOutline(playerid, TaiXiuTD[playerid][14], 1);
    PlayerTextDrawSetShadow(playerid, TaiXiuTD[playerid][14], 0);
    PlayerTextDrawAlignment(playerid, TaiXiuTD[playerid][14], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, TaiXiuTD[playerid][14], TX_COLOR_PINK);
    PlayerTextDrawBackgroundColour(playerid, TaiXiuTD[playerid][14], 255);
    PlayerTextDrawBoxColour(playerid, TaiXiuTD[playerid][14], 255);
    PlayerTextDrawUseBox(playerid, TaiXiuTD[playerid][14], bool:0);
    PlayerTextDrawSetProportional(playerid, TaiXiuTD[playerid][14], bool:1);
    PlayerTextDrawSetSelectable(playerid, TaiXiuTD[playerid][14], bool:0);

    TaiXiuTD[playerid][15] = CreatePlayerTextDraw(playerid, 125.0, 175.0, "HUD:radar_gangb");
    PlayerTextDrawFont(playerid, TaiXiuTD[playerid][15], TEXT_DRAW_FONT:4);
    PlayerTextDrawLetterSize(playerid, TaiXiuTD[playerid][15], 0.6, 2.0);
    PlayerTextDrawTextSize(playerid, TaiXiuTD[playerid][15], 21.5, 18.0);
    PlayerTextDrawSetOutline(playerid, TaiXiuTD[playerid][15], 1);
    PlayerTextDrawSetShadow(playerid, TaiXiuTD[playerid][15], 0);
    PlayerTextDrawAlignment(playerid, TaiXiuTD[playerid][15], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, TaiXiuTD[playerid][15], -1);
    PlayerTextDrawBackgroundColour(playerid, TaiXiuTD[playerid][15], 255);
    PlayerTextDrawBoxColour(playerid, TaiXiuTD[playerid][15], 50);
    PlayerTextDrawUseBox(playerid, TaiXiuTD[playerid][15], bool:1);
    PlayerTextDrawSetProportional(playerid, TaiXiuTD[playerid][15], bool:1);
    PlayerTextDrawSetSelectable(playerid, TaiXiuTD[playerid][15], bool:0);

    TaiXiuTD[playerid][16] = CreatePlayerTextDraw(playerid, 345.0, 175.0, "HUD:radar_gangb");
    PlayerTextDrawFont(playerid, TaiXiuTD[playerid][16], TEXT_DRAW_FONT:4);
    PlayerTextDrawLetterSize(playerid, TaiXiuTD[playerid][16], 0.6, 2.0);
    PlayerTextDrawTextSize(playerid, TaiXiuTD[playerid][16], 21.5, 18.0);
    PlayerTextDrawSetOutline(playerid, TaiXiuTD[playerid][16], 1);
    PlayerTextDrawSetShadow(playerid, TaiXiuTD[playerid][16], 0);
    PlayerTextDrawAlignment(playerid, TaiXiuTD[playerid][16], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, TaiXiuTD[playerid][16], -1);
    PlayerTextDrawBackgroundColour(playerid, TaiXiuTD[playerid][16], 255);
    PlayerTextDrawBoxColour(playerid, TaiXiuTD[playerid][16], 50);
    PlayerTextDrawUseBox(playerid, TaiXiuTD[playerid][16], bool:1);
    PlayerTextDrawSetProportional(playerid, TaiXiuTD[playerid][16], bool:1);
    PlayerTextDrawSetSelectable(playerid, TaiXiuTD[playerid][16], bool:0);

    TaiXiuTD[playerid][17] = CreatePlayerTextDraw(playerid, 234.0, 150.0, "Thoi Gian Cuoc");
    PlayerTextDrawFont(playerid, TaiXiuTD[playerid][17], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, TaiXiuTD[playerid][17], 0.2, 1.2);
    PlayerTextDrawTextSize(playerid, TaiXiuTD[playerid][17], 400.0, 64.5);
    PlayerTextDrawSetOutline(playerid, TaiXiuTD[playerid][17], 1);
    PlayerTextDrawSetShadow(playerid, TaiXiuTD[playerid][17], 0);
    PlayerTextDrawAlignment(playerid, TaiXiuTD[playerid][17], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, TaiXiuTD[playerid][17], -764862721);
    PlayerTextDrawBackgroundColour(playerid, TaiXiuTD[playerid][17], -3841);
    PlayerTextDrawBoxColour(playerid, TaiXiuTD[playerid][17], 50);
    PlayerTextDrawUseBox(playerid, TaiXiuTD[playerid][17], bool:0);
    PlayerTextDrawSetProportional(playerid, TaiXiuTD[playerid][17], bool:1);
    PlayerTextDrawSetSelectable(playerid, TaiXiuTD[playerid][17], bool:0);

    TaiXiuTD[playerid][18] = CreatePlayerTextDraw(playerid, 154.0, 291.0, "Toi Thieu Cuoc");
    PlayerTextDrawFont(playerid, TaiXiuTD[playerid][18], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, TaiXiuTD[playerid][18], 0.3, 1.1);
    PlayerTextDrawTextSize(playerid, TaiXiuTD[playerid][18], 399.5, 76.0);
    PlayerTextDrawSetOutline(playerid, TaiXiuTD[playerid][18], 1);
    PlayerTextDrawSetShadow(playerid, TaiXiuTD[playerid][18], 0);
    PlayerTextDrawAlignment(playerid, TaiXiuTD[playerid][18], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, TaiXiuTD[playerid][18], -1);
    PlayerTextDrawBackgroundColour(playerid, TaiXiuTD[playerid][18], 255);
    PlayerTextDrawBoxColour(playerid, TaiXiuTD[playerid][18], 50);
    PlayerTextDrawUseBox(playerid, TaiXiuTD[playerid][18], bool:0);
    PlayerTextDrawSetProportional(playerid, TaiXiuTD[playerid][18], bool:1);
    PlayerTextDrawSetSelectable(playerid, TaiXiuTD[playerid][18], bool:0);

    TaiXiuTD[playerid][19] = CreatePlayerTextDraw(playerid, 233.0, 291.0, "Toi Da Cuoc");
    PlayerTextDrawFont(playerid, TaiXiuTD[playerid][19], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, TaiXiuTD[playerid][19], 0.3, 1.1);
    PlayerTextDrawTextSize(playerid, TaiXiuTD[playerid][19], 399.5, 68.5);
    PlayerTextDrawSetOutline(playerid, TaiXiuTD[playerid][19], 1);
    PlayerTextDrawSetShadow(playerid, TaiXiuTD[playerid][19], 0);
    PlayerTextDrawAlignment(playerid, TaiXiuTD[playerid][19], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, TaiXiuTD[playerid][19], -1);
    PlayerTextDrawBackgroundColour(playerid, TaiXiuTD[playerid][19], 255);
    PlayerTextDrawBoxColour(playerid, TaiXiuTD[playerid][19], 50);
    PlayerTextDrawUseBox(playerid, TaiXiuTD[playerid][19], bool:0);
    PlayerTextDrawSetProportional(playerid, TaiXiuTD[playerid][19], bool:1);
    PlayerTextDrawSetSelectable(playerid, TaiXiuTD[playerid][19], bool:0);

    TaiXiuTD[playerid][20] = CreatePlayerTextDraw(playerid, 299.0, 291.0, "Phien");
    PlayerTextDrawFont(playerid, TaiXiuTD[playerid][20], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, TaiXiuTD[playerid][20], 0.3, 1.1);
    PlayerTextDrawTextSize(playerid, TaiXiuTD[playerid][20], 399.5, 51.0);
    PlayerTextDrawSetOutline(playerid, TaiXiuTD[playerid][20], 1);
    PlayerTextDrawSetShadow(playerid, TaiXiuTD[playerid][20], 0);
    PlayerTextDrawAlignment(playerid, TaiXiuTD[playerid][20], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, TaiXiuTD[playerid][20], -1);
    PlayerTextDrawBackgroundColour(playerid, TaiXiuTD[playerid][20], 255);
    PlayerTextDrawBoxColour(playerid, TaiXiuTD[playerid][20], 50);
    PlayerTextDrawUseBox(playerid, TaiXiuTD[playerid][20], bool:0);
    PlayerTextDrawSetProportional(playerid, TaiXiuTD[playerid][20], bool:1);
    PlayerTextDrawSetSelectable(playerid, TaiXiuTD[playerid][20], bool:0);

    // Hien trong thoi gian cuoc
    PicXucXac[playerid] = CreatePlayerTextDraw(playerid, 273.0, 146.0, "ld_tatt:11dice2");
    PlayerTextDrawFont(playerid, PicXucXac[playerid], TEXT_DRAW_FONT:4);
    PlayerTextDrawLetterSize(playerid, PicXucXac[playerid], 0.6, 2.0);
    PlayerTextDrawTextSize(playerid, PicXucXac[playerid], 49.5, 57.0);
    PlayerTextDrawSetOutline(playerid, PicXucXac[playerid], 1);
    PlayerTextDrawSetShadow(playerid, PicXucXac[playerid], 0);
    PlayerTextDrawAlignment(playerid, PicXucXac[playerid], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, PicXucXac[playerid], -1);
    PlayerTextDrawBackgroundColour(playerid, PicXucXac[playerid], 255);
    PlayerTextDrawBoxColour(playerid, PicXucXac[playerid], 50);
    PlayerTextDrawUseBox(playerid, PicXucXac[playerid], bool:1);
    PlayerTextDrawSetProportional(playerid, PicXucXac[playerid], bool:1);
    PlayerTextDrawSetSelectable(playerid, PicXucXac[playerid], bool:0);

    // hien ket qua cuoc
    formketqua[playerid] = CreatePlayerTextDraw(playerid, 298.0, 149.0, "TAI");
    PlayerTextDrawFont(playerid, formketqua[playerid], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, formketqua[playerid], 0.6, 5.4);
    PlayerTextDrawTextSize(playerid, formketqua[playerid], 298.5, 45.0);
    PlayerTextDrawSetOutline(playerid, formketqua[playerid], 1);
    PlayerTextDrawSetShadow(playerid, formketqua[playerid], 0);
    PlayerTextDrawAlignment(playerid, formketqua[playerid], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, formketqua[playerid], 255);
    PlayerTextDrawBackgroundColour(playerid, formketqua[playerid], -1094795521);
    PlayerTextDrawBoxColour(playerid, formketqua[playerid], -1378294017);
    PlayerTextDrawUseBox(playerid, formketqua[playerid], bool:1);
    PlayerTextDrawSetProportional(playerid, formketqua[playerid], bool:1);
    PlayerTextDrawSetSelectable(playerid, formketqua[playerid], bool:0);

    // hien ten top
    name_top[playerid][0] = CreatePlayerTextDraw(playerid, 435.0, 153.0, "Giap_Tran");
    PlayerTextDrawFont(playerid, name_top[playerid][0], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, name_top[playerid][0], 0.2, 0.8);
    PlayerTextDrawTextSize(playerid, name_top[playerid][0], 486.0, 7.0);
    PlayerTextDrawSetOutline(playerid, name_top[playerid][0], 1);
    PlayerTextDrawSetShadow(playerid, name_top[playerid][0], 0);
    PlayerTextDrawAlignment(playerid, name_top[playerid][0], TEXT_DRAW_ALIGN:1);
    PlayerTextDrawColour(playerid, name_top[playerid][0], -1);
    PlayerTextDrawBackgroundColour(playerid, name_top[playerid][0], 255);
    PlayerTextDrawBoxColour(playerid, name_top[playerid][0], 50);
    PlayerTextDrawUseBox(playerid, name_top[playerid][0], bool:0);
    PlayerTextDrawSetProportional(playerid, name_top[playerid][0], bool:1);
    PlayerTextDrawSetSelectable(playerid, name_top[playerid][0], bool:0);

    name_top[playerid][1] = CreatePlayerTextDraw(playerid, 435.0, 179.0, "Giap_Tran");
    PlayerTextDrawFont(playerid, name_top[playerid][1], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, name_top[playerid][1], 0.2, 0.8);
    PlayerTextDrawTextSize(playerid, name_top[playerid][1], 486.0, 7.0);
    PlayerTextDrawSetOutline(playerid, name_top[playerid][1], 1);
    PlayerTextDrawSetShadow(playerid, name_top[playerid][1], 0);
    PlayerTextDrawAlignment(playerid, name_top[playerid][1], TEXT_DRAW_ALIGN:1);
    PlayerTextDrawColour(playerid, name_top[playerid][1], -1);
    PlayerTextDrawBackgroundColour(playerid, name_top[playerid][1], 255);
    PlayerTextDrawBoxColour(playerid, name_top[playerid][1], 50);
    PlayerTextDrawUseBox(playerid, name_top[playerid][1], bool:0);
    PlayerTextDrawSetProportional(playerid, name_top[playerid][1], bool:1);
    PlayerTextDrawSetSelectable(playerid, name_top[playerid][1], bool:0);

    name_top[playerid][2] = CreatePlayerTextDraw(playerid, 435.0, 205.0, "Giap_Tran");
    PlayerTextDrawFont(playerid, name_top[playerid][2], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, name_top[playerid][2], 0.2, 0.8);
    PlayerTextDrawTextSize(playerid, name_top[playerid][2], 486.0, 7.0);
    PlayerTextDrawSetOutline(playerid, name_top[playerid][2], 1);
    PlayerTextDrawSetShadow(playerid, name_top[playerid][2], 0);
    PlayerTextDrawAlignment(playerid, name_top[playerid][2], TEXT_DRAW_ALIGN:1);
    PlayerTextDrawColour(playerid, name_top[playerid][2], -1);
    PlayerTextDrawBackgroundColour(playerid, name_top[playerid][2], 255);
    PlayerTextDrawBoxColour(playerid, name_top[playerid][2], 50);
    PlayerTextDrawUseBox(playerid, name_top[playerid][2], bool:0);
    PlayerTextDrawSetProportional(playerid, name_top[playerid][2], bool:1);
    PlayerTextDrawSetSelectable(playerid, name_top[playerid][2], bool:0);

    name_top[playerid][3] = CreatePlayerTextDraw(playerid, 435.0, 231.0, "Giap_Tran");
    PlayerTextDrawFont(playerid, name_top[playerid][3], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, name_top[playerid][3], 0.2, 0.8);
    PlayerTextDrawTextSize(playerid, name_top[playerid][3], 486.0, 7.0);
    PlayerTextDrawSetOutline(playerid, name_top[playerid][3], 1);
    PlayerTextDrawSetShadow(playerid, name_top[playerid][3], 0);
    PlayerTextDrawAlignment(playerid, name_top[playerid][3], TEXT_DRAW_ALIGN:1);
    PlayerTextDrawColour(playerid, name_top[playerid][3], -1);
    PlayerTextDrawBackgroundColour(playerid, name_top[playerid][3], 255);
    PlayerTextDrawBoxColour(playerid, name_top[playerid][3], 50);
    PlayerTextDrawUseBox(playerid, name_top[playerid][3], bool:0);
    PlayerTextDrawSetProportional(playerid, name_top[playerid][3], bool:1);
    PlayerTextDrawSetSelectable(playerid, name_top[playerid][3], bool:0);

    name_top[playerid][4] = CreatePlayerTextDraw(playerid, 435.0, 258.0, "Giap_Tran");
    PlayerTextDrawFont(playerid, name_top[playerid][4], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, name_top[playerid][4], 0.2, 0.8);
    PlayerTextDrawTextSize(playerid, name_top[playerid][4], 486.0, 7.0);
    PlayerTextDrawSetOutline(playerid, name_top[playerid][4], 1);
    PlayerTextDrawSetShadow(playerid, name_top[playerid][4], 0);
    PlayerTextDrawAlignment(playerid, name_top[playerid][4], TEXT_DRAW_ALIGN:1);
    PlayerTextDrawColour(playerid, name_top[playerid][4], -1);
    PlayerTextDrawBackgroundColour(playerid, name_top[playerid][4], 255);
    PlayerTextDrawBoxColour(playerid, name_top[playerid][4], 50);
    PlayerTextDrawUseBox(playerid, name_top[playerid][4], bool:0);
    PlayerTextDrawSetProportional(playerid, name_top[playerid][4], bool:1);
    PlayerTextDrawSetSelectable(playerid, name_top[playerid][4], bool:0);

    name_top[playerid][5] = CreatePlayerTextDraw(playerid, 435.0, 285.0, "Giap_Tran");
    PlayerTextDrawFont(playerid, name_top[playerid][5], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, name_top[playerid][5], 0.2, 0.8);
    PlayerTextDrawTextSize(playerid, name_top[playerid][5], 486.0, 7.0);
    PlayerTextDrawSetOutline(playerid, name_top[playerid][5], 1);
    PlayerTextDrawSetShadow(playerid, name_top[playerid][5], 0);
    PlayerTextDrawAlignment(playerid, name_top[playerid][5], TEXT_DRAW_ALIGN:1);
    PlayerTextDrawColour(playerid, name_top[playerid][5], -1);
    PlayerTextDrawBackgroundColour(playerid, name_top[playerid][5], 255);
    PlayerTextDrawBoxColour(playerid, name_top[playerid][5], 50);
    PlayerTextDrawUseBox(playerid, name_top[playerid][5], bool:0);
    PlayerTextDrawSetProportional(playerid, name_top[playerid][5], bool:1);
    PlayerTextDrawSetSelectable(playerid, name_top[playerid][5], bool:0);

    name_top[playerid][6] = CreatePlayerTextDraw(playerid, 435.0, 312.0, "Giap_Tran");
    PlayerTextDrawFont(playerid, name_top[playerid][6], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, name_top[playerid][6], 0.2, 0.8);
    PlayerTextDrawTextSize(playerid, name_top[playerid][6], 486.0, 7.0);
    PlayerTextDrawSetOutline(playerid, name_top[playerid][6], 1);
    PlayerTextDrawSetShadow(playerid, name_top[playerid][6], 0);
    PlayerTextDrawAlignment(playerid, name_top[playerid][6], TEXT_DRAW_ALIGN:1);
    PlayerTextDrawColour(playerid, name_top[playerid][6], -1);
    PlayerTextDrawBackgroundColour(playerid, name_top[playerid][6], 255);
    PlayerTextDrawBoxColour(playerid, name_top[playerid][6], 50);
    PlayerTextDrawUseBox(playerid, name_top[playerid][6], bool:0);
    PlayerTextDrawSetProportional(playerid, name_top[playerid][6], bool:1);
    PlayerTextDrawSetSelectable(playerid, name_top[playerid][6], bool:0);

    tien_top[playerid][0] = CreatePlayerTextDraw(playerid, 492.0, 153.0, "$12000000");
    PlayerTextDrawFont(playerid, tien_top[playerid][0], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, tien_top[playerid][0], 0.2, 0.8);
    PlayerTextDrawTextSize(playerid, tien_top[playerid][0], 521.5, 7.0);
    PlayerTextDrawSetOutline(playerid, tien_top[playerid][0], 1);
    PlayerTextDrawSetShadow(playerid, tien_top[playerid][0], 0);
    PlayerTextDrawAlignment(playerid, tien_top[playerid][0], TEXT_DRAW_ALIGN:1);
    PlayerTextDrawColour(playerid, tien_top[playerid][0], 16711935);
    PlayerTextDrawBackgroundColour(playerid, tien_top[playerid][0], 255);
    PlayerTextDrawBoxColour(playerid, tien_top[playerid][0], 50);
    PlayerTextDrawUseBox(playerid, tien_top[playerid][0], bool:0);
    PlayerTextDrawSetProportional(playerid, tien_top[playerid][0], bool:1);
    PlayerTextDrawSetSelectable(playerid, tien_top[playerid][0], bool:0);

    tien_top[playerid][1] = CreatePlayerTextDraw(playerid, 492.0, 179.0, "$12000000");
    PlayerTextDrawFont(playerid, tien_top[playerid][1], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, tien_top[playerid][1], 0.2, 0.8);
    PlayerTextDrawTextSize(playerid, tien_top[playerid][1], 521.5, 7.0);
    PlayerTextDrawSetOutline(playerid, tien_top[playerid][1], 1);
    PlayerTextDrawSetShadow(playerid, tien_top[playerid][1], 0);
    PlayerTextDrawAlignment(playerid, tien_top[playerid][1], TEXT_DRAW_ALIGN:1);
    PlayerTextDrawColour(playerid, tien_top[playerid][1], 16711935);
    PlayerTextDrawBackgroundColour(playerid, tien_top[playerid][1], 255);
    PlayerTextDrawBoxColour(playerid, tien_top[playerid][1], 50);
    PlayerTextDrawUseBox(playerid, tien_top[playerid][1], bool:0);
    PlayerTextDrawSetProportional(playerid, tien_top[playerid][1], bool:1);
    PlayerTextDrawSetSelectable(playerid, tien_top[playerid][1], bool:0);

    tien_top[playerid][2] = CreatePlayerTextDraw(playerid, 492.0, 205.0, "$12000000");
    PlayerTextDrawFont(playerid, tien_top[playerid][2], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, tien_top[playerid][2], 0.2, 0.8);
    PlayerTextDrawTextSize(playerid, tien_top[playerid][2], 521.5, 7.0);
    PlayerTextDrawSetOutline(playerid, tien_top[playerid][2], 1);
    PlayerTextDrawSetShadow(playerid, tien_top[playerid][2], 0);
    PlayerTextDrawAlignment(playerid, tien_top[playerid][2], TEXT_DRAW_ALIGN:1);
    PlayerTextDrawColour(playerid, tien_top[playerid][2], 16711935);
    PlayerTextDrawBackgroundColour(playerid, tien_top[playerid][2], 255);
    PlayerTextDrawBoxColour(playerid, tien_top[playerid][2], 50);
    PlayerTextDrawUseBox(playerid, tien_top[playerid][2], bool:0);
    PlayerTextDrawSetProportional(playerid, tien_top[playerid][2], bool:1);
    PlayerTextDrawSetSelectable(playerid, tien_top[playerid][2], bool:0);

    tien_top[playerid][3] = CreatePlayerTextDraw(playerid, 492.0, 231.0, "$12000000");
    PlayerTextDrawFont(playerid, tien_top[playerid][3], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, tien_top[playerid][3], 0.2, 0.8);
    PlayerTextDrawTextSize(playerid, tien_top[playerid][3], 521.5, 7.0);
    PlayerTextDrawSetOutline(playerid, tien_top[playerid][3], 1);
    PlayerTextDrawSetShadow(playerid, tien_top[playerid][3], 0);
    PlayerTextDrawAlignment(playerid, tien_top[playerid][3], TEXT_DRAW_ALIGN:1);
    PlayerTextDrawColour(playerid, tien_top[playerid][3], 16711935);
    PlayerTextDrawBackgroundColour(playerid, tien_top[playerid][3], 255);
    PlayerTextDrawBoxColour(playerid, tien_top[playerid][3], 50);
    PlayerTextDrawUseBox(playerid, tien_top[playerid][3], bool:0);
    PlayerTextDrawSetProportional(playerid, tien_top[playerid][3], bool:1);
    PlayerTextDrawSetSelectable(playerid, tien_top[playerid][3], bool:0);

    tien_top[playerid][4] = CreatePlayerTextDraw(playerid, 492.0, 258.0, "$12000000");
    PlayerTextDrawFont(playerid, tien_top[playerid][4], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, tien_top[playerid][4], 0.2, 0.8);
    PlayerTextDrawTextSize(playerid, tien_top[playerid][4], 521.5, 7.0);
    PlayerTextDrawSetOutline(playerid, tien_top[playerid][4], 1);
    PlayerTextDrawSetShadow(playerid, tien_top[playerid][4], 0);
    PlayerTextDrawAlignment(playerid, tien_top[playerid][4], TEXT_DRAW_ALIGN:1);
    PlayerTextDrawColour(playerid, tien_top[playerid][4], 16711935);
    PlayerTextDrawBackgroundColour(playerid, tien_top[playerid][4], 255);
    PlayerTextDrawBoxColour(playerid, tien_top[playerid][4], 50);
    PlayerTextDrawUseBox(playerid, tien_top[playerid][4], bool:0);
    PlayerTextDrawSetProportional(playerid, tien_top[playerid][4], bool:1);
    PlayerTextDrawSetSelectable(playerid, tien_top[playerid][4], bool:0);

    tien_top[playerid][5] = CreatePlayerTextDraw(playerid, 492.0, 285.0, "$12000000");
    PlayerTextDrawFont(playerid, tien_top[playerid][5], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, tien_top[playerid][5], 0.2, 0.8);
    PlayerTextDrawTextSize(playerid, tien_top[playerid][5], 521.5, 7.0);
    PlayerTextDrawSetOutline(playerid, tien_top[playerid][5], 1);
    PlayerTextDrawSetShadow(playerid, tien_top[playerid][5], 0);
    PlayerTextDrawAlignment(playerid, tien_top[playerid][5], TEXT_DRAW_ALIGN:1);
    PlayerTextDrawColour(playerid, tien_top[playerid][5], 16711935);
    PlayerTextDrawBackgroundColour(playerid, tien_top[playerid][5], 255);
    PlayerTextDrawBoxColour(playerid, tien_top[playerid][5], 50);
    PlayerTextDrawUseBox(playerid, tien_top[playerid][5], bool:0);
    PlayerTextDrawSetProportional(playerid, tien_top[playerid][5], bool:1);
    PlayerTextDrawSetSelectable(playerid, tien_top[playerid][5], bool:0);

    tien_top[playerid][6] = CreatePlayerTextDraw(playerid, 492.0, 312.0, "$12000000");
    PlayerTextDrawFont(playerid, tien_top[playerid][6], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, tien_top[playerid][6], 0.2, 0.8);
    PlayerTextDrawTextSize(playerid, tien_top[playerid][6], 521.5, 7.0);
    PlayerTextDrawSetOutline(playerid, tien_top[playerid][6], 1);
    PlayerTextDrawSetShadow(playerid, tien_top[playerid][6], 0);
    PlayerTextDrawAlignment(playerid, tien_top[playerid][6], TEXT_DRAW_ALIGN:1);
    PlayerTextDrawColour(playerid, tien_top[playerid][6], 16711935);
    PlayerTextDrawBackgroundColour(playerid, tien_top[playerid][6], 255);
    PlayerTextDrawBoxColour(playerid, tien_top[playerid][6], 50);
    PlayerTextDrawUseBox(playerid, tien_top[playerid][6], bool:0);
    PlayerTextDrawSetProportional(playerid, tien_top[playerid][6], bool:1);
    PlayerTextDrawSetSelectable(playerid, tien_top[playerid][6], bool:0);

    // Thoi gian cuoc dem nguoc
    thoigiancuoc[playerid] = CreatePlayerTextDraw(playerid, 234.0, 174.0, "30");
    PlayerTextDrawFont(playerid, thoigiancuoc[playerid], TEXT_DRAW_FONT:2);
    PlayerTextDrawLetterSize(playerid, thoigiancuoc[playerid], 0.7, 2.5);
    PlayerTextDrawTextSize(playerid, thoigiancuoc[playerid], 400.0, 39.0);
    PlayerTextDrawSetOutline(playerid, thoigiancuoc[playerid], 1);
    PlayerTextDrawSetShadow(playerid, thoigiancuoc[playerid], 0);
    PlayerTextDrawAlignment(playerid, thoigiancuoc[playerid], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, thoigiancuoc[playerid], 1687547391);
    PlayerTextDrawBackgroundColour(playerid, thoigiancuoc[playerid], 2094792959);
    PlayerTextDrawBoxColour(playerid, thoigiancuoc[playerid], 50);
    PlayerTextDrawUseBox(playerid, thoigiancuoc[playerid], bool:0);
    PlayerTextDrawSetProportional(playerid, thoigiancuoc[playerid], bool:1);
    PlayerTextDrawSetSelectable(playerid, thoigiancuoc[playerid], bool:0);
    
    songuoicuocTai[playerid] = CreatePlayerTextDraw(playerid, 161.0, 178.0, "100");
    PlayerTextDrawFont(playerid, songuoicuocTai[playerid], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, songuoicuocTai[playerid], 0.3, 1.2);
    PlayerTextDrawTextSize(playerid, songuoicuocTai[playerid], 400.0, 17.0);
    PlayerTextDrawSetOutline(playerid, songuoicuocTai[playerid], 1);
    PlayerTextDrawSetShadow(playerid, songuoicuocTai[playerid], 0);
    PlayerTextDrawAlignment(playerid, songuoicuocTai[playerid], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, songuoicuocTai[playerid], -1);
    PlayerTextDrawBackgroundColour(playerid, songuoicuocTai[playerid], 255);
    PlayerTextDrawBoxColour(playerid, songuoicuocTai[playerid], 50);
    PlayerTextDrawUseBox(playerid, songuoicuocTai[playerid], bool:0);
    PlayerTextDrawSetProportional(playerid, songuoicuocTai[playerid], bool:1);
    PlayerTextDrawSetSelectable(playerid, songuoicuocTai[playerid], bool:0);

    songuoicuocXiu[playerid] = CreatePlayerTextDraw(playerid, 381.0, 178.0, "100");
    PlayerTextDrawFont(playerid, songuoicuocXiu[playerid], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, songuoicuocXiu[playerid], 0.3, 1.2);
    PlayerTextDrawTextSize(playerid, songuoicuocXiu[playerid], 400.0, 17.0);
    PlayerTextDrawSetOutline(playerid, songuoicuocXiu[playerid], 1);
    PlayerTextDrawSetShadow(playerid, songuoicuocXiu[playerid], 0);
    PlayerTextDrawAlignment(playerid, songuoicuocXiu[playerid], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, songuoicuocXiu[playerid], -1);
    PlayerTextDrawBackgroundColour(playerid, songuoicuocXiu[playerid], 255);
    PlayerTextDrawBoxColour(playerid, songuoicuocXiu[playerid], 50);
    PlayerTextDrawUseBox(playerid, songuoicuocXiu[playerid], bool:0);
    PlayerTextDrawSetProportional(playerid, songuoicuocXiu[playerid], bool:1);
    PlayerTextDrawSetSelectable(playerid, songuoicuocXiu[playerid], bool:0);

    // Array Lich Su Phien
    LSuPhien[playerid][0] = CreatePlayerTextDraw(playerid, 209.0, 245.0, "-"); // T
    PlayerTextDrawFont(playerid, LSuPhien[playerid][0], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, LSuPhien[playerid][0], 0.5, 1.3);
    PlayerTextDrawTextSize(playerid, LSuPhien[playerid][0], 400.0, 17.0);
    PlayerTextDrawSetOutline(playerid, LSuPhien[playerid][0], 1);
    PlayerTextDrawSetShadow(playerid, LSuPhien[playerid][0], 0);
    PlayerTextDrawAlignment(playerid, LSuPhien[playerid][0], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, LSuPhien[playerid][0], 65535);
    PlayerTextDrawBackgroundColour(playerid, LSuPhien[playerid][0], 255);
    PlayerTextDrawBoxColour(playerid, LSuPhien[playerid][0], 29);
    PlayerTextDrawUseBox(playerid, LSuPhien[playerid][0], bool:1);
    PlayerTextDrawSetProportional(playerid, LSuPhien[playerid][0], bool:1);
    PlayerTextDrawSetSelectable(playerid, LSuPhien[playerid][0], bool:0);

    LSuPhien[playerid][1] = CreatePlayerTextDraw(playerid, 236.0, 245.0, "-"); // X
    PlayerTextDrawFont(playerid, LSuPhien[playerid][1], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, LSuPhien[playerid][1], 0.5, 1.3);
    PlayerTextDrawTextSize(playerid, LSuPhien[playerid][1], 400.0, 17.0);
    PlayerTextDrawSetOutline(playerid, LSuPhien[playerid][1], 1);
    PlayerTextDrawSetShadow(playerid, LSuPhien[playerid][1], 0);
    PlayerTextDrawAlignment(playerid, LSuPhien[playerid][1], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, LSuPhien[playerid][1], -16776961);
    PlayerTextDrawBackgroundColour(playerid, LSuPhien[playerid][1], 255);
    PlayerTextDrawBoxColour(playerid, LSuPhien[playerid][1], 29);
    PlayerTextDrawUseBox(playerid, LSuPhien[playerid][1], bool:1);
    PlayerTextDrawSetProportional(playerid, LSuPhien[playerid][1], bool:1);
    PlayerTextDrawSetSelectable(playerid, LSuPhien[playerid][1], bool:0);

    LSuPhien[playerid][2] = CreatePlayerTextDraw(playerid, 263.0, 245.0, "-"); // X
    PlayerTextDrawFont(playerid, LSuPhien[playerid][2], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, LSuPhien[playerid][2], 0.5, 1.3);
    PlayerTextDrawTextSize(playerid, LSuPhien[playerid][2], 400.0, 17.0);
    PlayerTextDrawSetOutline(playerid, LSuPhien[playerid][2], 1);
    PlayerTextDrawSetShadow(playerid, LSuPhien[playerid][2], 0);
    PlayerTextDrawAlignment(playerid, LSuPhien[playerid][2], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, LSuPhien[playerid][2], -16776961);
    PlayerTextDrawBackgroundColour(playerid, LSuPhien[playerid][2], 255);
    PlayerTextDrawBoxColour(playerid, LSuPhien[playerid][2], 29);
    PlayerTextDrawUseBox(playerid, LSuPhien[playerid][2], bool:1);
    PlayerTextDrawSetProportional(playerid, LSuPhien[playerid][2], bool:1);
    PlayerTextDrawSetSelectable(playerid, LSuPhien[playerid][2], bool:0);

    LSuPhien[playerid][3] = CreatePlayerTextDraw(playerid, 290.0, 245.0, "-"); // T
    PlayerTextDrawFont(playerid, LSuPhien[playerid][3], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, LSuPhien[playerid][3], 0.5, 1.3);
    PlayerTextDrawTextSize(playerid, LSuPhien[playerid][3], 400.0, 17.0);
    PlayerTextDrawSetOutline(playerid, LSuPhien[playerid][3], 1);
    PlayerTextDrawSetShadow(playerid, LSuPhien[playerid][3], 0);
    PlayerTextDrawAlignment(playerid, LSuPhien[playerid][3], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, LSuPhien[playerid][3], 65535);
    PlayerTextDrawBackgroundColour(playerid, LSuPhien[playerid][3], 255);
    PlayerTextDrawBoxColour(playerid, LSuPhien[playerid][3], 29);
    PlayerTextDrawUseBox(playerid, LSuPhien[playerid][3], bool:1);
    PlayerTextDrawSetProportional(playerid, LSuPhien[playerid][3], bool:1);
    PlayerTextDrawSetSelectable(playerid, LSuPhien[playerid][3], bool:0);

    LSuPhien[playerid][4] = CreatePlayerTextDraw(playerid, 317.0, 245.0, "-"); // T
    PlayerTextDrawFont(playerid, LSuPhien[playerid][4], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, LSuPhien[playerid][4], 0.5, 1.3);
    PlayerTextDrawTextSize(playerid, LSuPhien[playerid][4], 400.0, 17.0);
    PlayerTextDrawSetOutline(playerid, LSuPhien[playerid][4], 1);
    PlayerTextDrawSetShadow(playerid, LSuPhien[playerid][4], 0);
    PlayerTextDrawAlignment(playerid, LSuPhien[playerid][4], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, LSuPhien[playerid][4], 65535);
    PlayerTextDrawBackgroundColour(playerid, LSuPhien[playerid][4], 255);
    PlayerTextDrawBoxColour(playerid, LSuPhien[playerid][4], 29);
    PlayerTextDrawUseBox(playerid, LSuPhien[playerid][4], bool:1);
    PlayerTextDrawSetProportional(playerid, LSuPhien[playerid][4], bool:1);
    PlayerTextDrawSetSelectable(playerid, LSuPhien[playerid][4], bool:0);

    // Button
    btn_lsuphien[playerid] = CreatePlayerTextDraw(playerid, 263.0, 222.0, "Lich Su Phien");
    PlayerTextDrawFont(playerid, btn_lsuphien[playerid], TEXT_DRAW_FONT:2);
    PlayerTextDrawLetterSize(playerid, btn_lsuphien[playerid], 0.2, 0.8);
    PlayerTextDrawTextSize(playerid, btn_lsuphien[playerid], 13.5, 122.0);
    PlayerTextDrawSetOutline(playerid, btn_lsuphien[playerid], 1);
    PlayerTextDrawSetShadow(playerid, btn_lsuphien[playerid], 0);
    PlayerTextDrawAlignment(playerid, btn_lsuphien[playerid], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, btn_lsuphien[playerid], TX_COLOR_PINK);
    PlayerTextDrawBackgroundColour(playerid, btn_lsuphien[playerid], 255);
    PlayerTextDrawBoxColour(playerid, btn_lsuphien[playerid], 33);
    PlayerTextDrawUseBox(playerid, btn_lsuphien[playerid], bool:1);
    PlayerTextDrawSetProportional(playerid, btn_lsuphien[playerid], bool:1);
    PlayerTextDrawSetSelectable(playerid, btn_lsuphien[playerid], bool:1);

    btn_cuocTai[playerid] = CreatePlayerTextDraw(playerid, 151.0, 242.0, "Dat Cuoc");
    PlayerTextDrawFont(playerid, btn_cuocTai[playerid], TEXT_DRAW_FONT:2);
    PlayerTextDrawLetterSize(playerid, btn_cuocTai[playerid], 0.1, 0.8);
    PlayerTextDrawTextSize(playerid, btn_cuocTai[playerid], 14.5, 28.5);
    PlayerTextDrawSetOutline(playerid, btn_cuocTai[playerid], 1);
    PlayerTextDrawSetShadow(playerid, btn_cuocTai[playerid], 0);
    PlayerTextDrawAlignment(playerid, btn_cuocTai[playerid], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, btn_cuocTai[playerid], -1);
    PlayerTextDrawBackgroundColour(playerid, btn_cuocTai[playerid], -256);
    PlayerTextDrawBoxColour(playerid, btn_cuocTai[playerid], 65449);
    PlayerTextDrawUseBox(playerid, btn_cuocTai[playerid], bool:1);
    PlayerTextDrawSetProportional(playerid, btn_cuocTai[playerid], bool:1);
    PlayerTextDrawSetSelectable(playerid, btn_cuocTai[playerid], bool:1);

    btn_cuocXiu[playerid] = CreatePlayerTextDraw(playerid, 371.0, 242.0, "Dat Cuoc");
    PlayerTextDrawFont(playerid, btn_cuocXiu[playerid], TEXT_DRAW_FONT:2);
    PlayerTextDrawLetterSize(playerid, btn_cuocXiu[playerid], 0.1, 0.8);
    PlayerTextDrawTextSize(playerid, btn_cuocXiu[playerid], 14.5, 28.5);
    PlayerTextDrawSetOutline(playerid, btn_cuocXiu[playerid], 1);
    PlayerTextDrawSetShadow(playerid, btn_cuocXiu[playerid], 0);
    PlayerTextDrawAlignment(playerid, btn_cuocXiu[playerid], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, btn_cuocXiu[playerid], -1);
    PlayerTextDrawBackgroundColour(playerid, btn_cuocXiu[playerid], -256);
    PlayerTextDrawBoxColour(playerid, btn_cuocXiu[playerid], -16777047);
    PlayerTextDrawUseBox(playerid, btn_cuocXiu[playerid], bool:1);
    PlayerTextDrawSetProportional(playerid, btn_cuocXiu[playerid], bool:1);
    PlayerTextDrawSetSelectable(playerid, btn_cuocXiu[playerid], bool:1);

    btn_thuhoicuoc[playerid] = CreatePlayerTextDraw(playerid, 263.0, 272.0, "Thu Hoi Cuoc");
    PlayerTextDrawFont(playerid, btn_thuhoicuoc[playerid], TEXT_DRAW_FONT:2);
    PlayerTextDrawLetterSize(playerid, btn_thuhoicuoc[playerid], 0.1, 0.8);
    PlayerTextDrawTextSize(playerid, btn_thuhoicuoc[playerid], 14.5, 43.5);
    PlayerTextDrawSetOutline(playerid, btn_thuhoicuoc[playerid], 1);
    PlayerTextDrawSetShadow(playerid, btn_thuhoicuoc[playerid], 0);
    PlayerTextDrawAlignment(playerid, btn_thuhoicuoc[playerid], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, btn_thuhoicuoc[playerid], TX_COLOR_WHITE);
    PlayerTextDrawBackgroundColour(playerid, btn_thuhoicuoc[playerid], -256);
    PlayerTextDrawBoxColour(playerid, btn_thuhoicuoc[playerid], -1061109701);
    PlayerTextDrawUseBox(playerid, btn_thuhoicuoc[playerid], bool:1);
    PlayerTextDrawSetProportional(playerid, btn_thuhoicuoc[playerid], bool:1);
    PlayerTextDrawSetSelectable(playerid, btn_thuhoicuoc[playerid], bool:1);

    btn_roiban[playerid] = CreatePlayerTextDraw(playerid, 370.0, 292.0, "Roi Ban");
    PlayerTextDrawFont(playerid, btn_roiban[playerid], TEXT_DRAW_FONT:2);
    PlayerTextDrawLetterSize(playerid, btn_roiban[playerid], 0.1, 0.8);
    PlayerTextDrawTextSize(playerid, btn_roiban[playerid], 14.5, 28.5);
    PlayerTextDrawSetOutline(playerid, btn_roiban[playerid], 1);
    PlayerTextDrawSetShadow(playerid, btn_roiban[playerid], 0);
    PlayerTextDrawAlignment(playerid, btn_roiban[playerid], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, btn_roiban[playerid], TX_COLOR_XIU);
    PlayerTextDrawBackgroundColour(playerid, btn_roiban[playerid], -256);
    PlayerTextDrawBoxColour(playerid, btn_roiban[playerid], 9145227);
    PlayerTextDrawUseBox(playerid, btn_roiban[playerid], bool:1);
    PlayerTextDrawSetProportional(playerid, btn_roiban[playerid], bool:1);
    PlayerTextDrawSetSelectable(playerid, btn_roiban[playerid], bool:1);

    // Text Draw Tien Cuoc
    tiendattai[playerid] = CreatePlayerTextDraw(playerid, 153.0, 216.0, "100000000");
    PlayerTextDrawFont(playerid, tiendattai[playerid], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, tiendattai[playerid], 0.3, 0.8);
    PlayerTextDrawTextSize(playerid, tiendattai[playerid], 400.0, 74.0);
    PlayerTextDrawSetOutline(playerid, tiendattai[playerid], 1);
    PlayerTextDrawSetShadow(playerid, tiendattai[playerid], 0);
    PlayerTextDrawAlignment(playerid, tiendattai[playerid], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, tiendattai[playerid], -1);
    PlayerTextDrawBackgroundColour(playerid, tiendattai[playerid], 255);
    PlayerTextDrawBoxColour(playerid, tiendattai[playerid], -246);
    PlayerTextDrawUseBox(playerid, tiendattai[playerid], bool:1);
    PlayerTextDrawSetProportional(playerid, tiendattai[playerid], bool:1);
    PlayerTextDrawSetSelectable(playerid, tiendattai[playerid], bool:0);

    tiendatxiu[playerid] = CreatePlayerTextDraw(playerid, 372.0, 216.0, "100000000");
    PlayerTextDrawFont(playerid, tiendatxiu[playerid], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, tiendatxiu[playerid], 0.3, 0.8);
    PlayerTextDrawTextSize(playerid, tiendatxiu[playerid], 400.0, 74.0);
    PlayerTextDrawSetOutline(playerid, tiendatxiu[playerid], 1);
    PlayerTextDrawSetShadow(playerid, tiendatxiu[playerid], 0);
    PlayerTextDrawAlignment(playerid, tiendatxiu[playerid], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, tiendatxiu[playerid], -1);
    PlayerTextDrawBackgroundColour(playerid, tiendatxiu[playerid], 255);
    PlayerTextDrawBoxColour(playerid, tiendatxiu[playerid], -246);
    PlayerTextDrawUseBox(playerid, tiendatxiu[playerid], bool:1);
    PlayerTextDrawSetProportional(playerid, tiendatxiu[playerid], bool:1);
    PlayerTextDrawSetSelectable(playerid, tiendatxiu[playerid], bool:0);

    tongtiencuoctai[playerid] = CreatePlayerTextDraw(playerid, 153.0, 147.0, "10000000000");
    PlayerTextDrawFont(playerid, tongtiencuoctai[playerid], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, tongtiencuoctai[playerid], 0.2, 1.3);
    PlayerTextDrawTextSize(playerid, tongtiencuoctai[playerid], 400.0, 74.0);
    PlayerTextDrawSetOutline(playerid, tongtiencuoctai[playerid], 1);
    PlayerTextDrawSetShadow(playerid, tongtiencuoctai[playerid], 0);
    PlayerTextDrawAlignment(playerid, tongtiencuoctai[playerid], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, tongtiencuoctai[playerid], 16711935);
    PlayerTextDrawBackgroundColour(playerid, tongtiencuoctai[playerid], 255);
    PlayerTextDrawBoxColour(playerid, tongtiencuoctai[playerid], -246);
    PlayerTextDrawUseBox(playerid, tongtiencuoctai[playerid], bool:0);
    PlayerTextDrawSetProportional(playerid, tongtiencuoctai[playerid], bool:1);
    PlayerTextDrawSetSelectable(playerid, tongtiencuoctai[playerid], bool:0);

    tongtiencuocxiu[playerid] = CreatePlayerTextDraw(playerid, 372.0, 147.0, "10000000000");
    PlayerTextDrawFont(playerid, tongtiencuocxiu[playerid], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, tongtiencuocxiu[playerid], 0.2, 1.3);
    PlayerTextDrawTextSize(playerid, tongtiencuocxiu[playerid], 400.0, 74.0);
    PlayerTextDrawSetOutline(playerid, tongtiencuocxiu[playerid], 1);
    PlayerTextDrawSetShadow(playerid, tongtiencuocxiu[playerid], 0);
    PlayerTextDrawAlignment(playerid, tongtiencuocxiu[playerid], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, tongtiencuocxiu[playerid], 16711935);
    PlayerTextDrawBackgroundColour(playerid, tongtiencuocxiu[playerid], 255);
    PlayerTextDrawBoxColour(playerid, tongtiencuocxiu[playerid], -246);
    PlayerTextDrawUseBox(playerid, tongtiencuocxiu[playerid], bool:0);
    PlayerTextDrawSetProportional(playerid, tongtiencuocxiu[playerid], bool:1);
    PlayerTextDrawSetSelectable(playerid, tongtiencuocxiu[playerid], bool:0);

    tiencuoc_min[playerid] = CreatePlayerTextDraw(playerid, 153.0, 309.0, "$100000000");
    PlayerTextDrawFont(playerid, tiencuoc_min[playerid], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, tiencuoc_min[playerid], 0.3, 0.8);
    PlayerTextDrawTextSize(playerid, tiencuoc_min[playerid], 400.0, 74.0);
    PlayerTextDrawSetOutline(playerid, tiencuoc_min[playerid], 1);
    PlayerTextDrawSetShadow(playerid, tiencuoc_min[playerid], 0);
    PlayerTextDrawAlignment(playerid, tiencuoc_min[playerid], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, tiencuoc_min[playerid], TX_COLOR_GREEN);
    PlayerTextDrawBackgroundColour(playerid, tiencuoc_min[playerid], 255);
    PlayerTextDrawBoxColour(playerid, tiencuoc_min[playerid], -246);
    PlayerTextDrawUseBox(playerid, tiencuoc_min[playerid], bool:1);
    PlayerTextDrawSetProportional(playerid, tiencuoc_min[playerid], bool:1);
    PlayerTextDrawSetSelectable(playerid, tiencuoc_min[playerid], bool:0);

    tiencuoc_max[playerid] = CreatePlayerTextDraw(playerid, 232.0, 309.0, "$100000000");
    PlayerTextDrawFont(playerid, tiencuoc_max[playerid], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, tiencuoc_max[playerid], 0.3, 0.8);
    PlayerTextDrawTextSize(playerid, tiencuoc_max[playerid], 400.0, 74.0);
    PlayerTextDrawSetOutline(playerid, tiencuoc_max[playerid], 1);
    PlayerTextDrawSetShadow(playerid, tiencuoc_max[playerid], 0);
    PlayerTextDrawAlignment(playerid, tiencuoc_max[playerid], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, tiencuoc_max[playerid], TX_COLOR_GREEN);
    PlayerTextDrawBackgroundColour(playerid, tiencuoc_max[playerid], 255);
    PlayerTextDrawBoxColour(playerid, tiencuoc_max[playerid], -246);
    PlayerTextDrawUseBox(playerid, tiencuoc_max[playerid], bool:1);
    PlayerTextDrawSetProportional(playerid, tiencuoc_max[playerid], bool:1);
    PlayerTextDrawSetSelectable(playerid, tiencuoc_max[playerid], bool:0);

    id_phiencuoc[playerid] = CreatePlayerTextDraw(playerid, 299.0, 309.0, "#12323");
    PlayerTextDrawFont(playerid, id_phiencuoc[playerid], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, id_phiencuoc[playerid], 0.3, 0.8);
    PlayerTextDrawTextSize(playerid, id_phiencuoc[playerid], 400.0, 50.0);
    PlayerTextDrawSetOutline(playerid, id_phiencuoc[playerid], 1);
    PlayerTextDrawSetShadow(playerid, id_phiencuoc[playerid], 0);
    PlayerTextDrawAlignment(playerid, id_phiencuoc[playerid], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, id_phiencuoc[playerid], TX_COLOR_GREEN);
    PlayerTextDrawBackgroundColour(playerid, id_phiencuoc[playerid], 255);
    PlayerTextDrawBoxColour(playerid, id_phiencuoc[playerid], -246);
    PlayerTextDrawUseBox(playerid, id_phiencuoc[playerid], bool:1);
    PlayerTextDrawSetProportional(playerid, id_phiencuoc[playerid], bool:1);
    PlayerTextDrawSetSelectable(playerid, id_phiencuoc[playerid], bool:0);

    TX_ThongBao[playerid] = CreatePlayerTextDraw(playerid, 320.0, 95.0, "_");
    PlayerTextDrawFont(playerid, TX_ThongBao[playerid], TEXT_DRAW_FONT:1);
    PlayerTextDrawLetterSize(playerid, TX_ThongBao[playerid], 0.2, 0.0);
    PlayerTextDrawTextSize(playerid, TX_ThongBao[playerid], 298.5, 415.0);
    PlayerTextDrawSetOutline(playerid, TX_ThongBao[playerid], 1);
    PlayerTextDrawSetShadow(playerid, TX_ThongBao[playerid], 0);
    PlayerTextDrawAlignment(playerid, TX_ThongBao[playerid], TEXT_DRAW_ALIGN:2);
    PlayerTextDrawColour(playerid, TX_ThongBao[playerid], -1);
    PlayerTextDrawBackgroundColour(playerid, TX_ThongBao[playerid], 255);
    PlayerTextDrawBoxColour(playerid, TX_ThongBao[playerid], 9145343);
    PlayerTextDrawUseBox(playerid, TX_ThongBao[playerid], bool:1);
    PlayerTextDrawSetProportional(playerid, TX_ThongBao[playerid], bool:1);
    PlayerTextDrawSetSelectable(playerid, TX_ThongBao[playerid], bool:0);

    return 1;
}